apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeployment
spec:
 replicas: 3
 minReadySeconds: 10
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1
 selector:
  matchLabels:
   type: webservers
 template:
   metadata:
    name: mypod
    labels:
     type: webservers
   spec:
    containers:
     - name: c1
       image: leaddevops/kubeserve:v1
       
---
apiVersion: v1
kind: Service
metadata:
 name: myservice
spec:
 type: NodePort
 ports: 
  - targetPort: 80
    port: 8181
    NodePort: 30009
 selector:
  matchLabels:
   type: webservers
   
