
apiVersion: apps/v1
kind: Deployment
metadata:
 name: kubedeployment
spec:
 replicas: 3
 minReadySeconds: 10
 strategy:
  type: RollingUpdate
  rollingupdate:
   maxUnavailable: 1
   maxSurge: 1
  
 selector:
  matchLables:
   type: kubeservers
 template:
  metadata:
   name: kubeservers
   labels:
    type: kubeservers
  spec:
   containers:
    - name: App
      image: leaddevops/kubeserve:v1
      
  ---
  apiVersion: v1
  kind: Service
  metadata:
   name: myservice
  spec:
   type: NodePort
   ports:
    - targetPort: 80
      port: 8181
      nodePort: 30009
    selector:
     matchLabels:
      type: kubeservers
      
   
  
